# Generated by Django 5.0.7 on 2024-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originial_url', models.URLField()),
                ('short_url', models.CharField(max_length=50)),
                ('time_daate_created', models.DateTimeField()),
            ],
        ),
    ]
