# Generated by Django 5.0.7 on 2024-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='time_daate_created',
            new_name='time_date_created',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='originial_url',
            field=models.URLField(max_length=700),
        ),
    ]
