# Generated by Django 5.0.7 on 2024-08-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0002_rename_time_daate_created_shorturl_time_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='originial_url',
            new_name='original_url',
        ),
    ]
